/*
-- Query: SELECT * FROM musephoria.cd
LIMIT 0, 400

-- Date: 2015-10-30 23:05
*/
INSERT INTO `cd` (`CdId`,`Name`,`Description`,`Price`,`Quantity`,`Genre`,`Artist`,`Year`,`Rating`,`Review`,`Language`,`NumberOfTrack`,`AlbumArt`,`IsCdActive`) VALUES (1001,'American Idiot','American Idiot is the seventh studio album by American rock band Green Day. Produced by Rob Cavallo, the album was released on September 20, 2004 by Reprise Records',12,25,'Rock','Green Day',2004,'Excellent','Excellent','Englisg',10,NULL,1);
INSERT INTO `cd` (`CdId`,`Name`,`Description`,`Price`,`Quantity`,`Genre`,`Artist`,`Year`,`Rating`,`Review`,`Language`,`NumberOfTrack`,`AlbumArt`,`IsCdActive`) VALUES (1002,'Lost Highway','Lost Highway is the tenth studio album by American rock band Bon Jovi. Produced by John Shanks and Dann Huff the album was recorded at Black Bird Studios, Nashville and NGR Recording, Hollywood.',10,10,'Rock','Jon Bon Jovi',2007,'Very Good','Good Music','English',12,NULL,1);
INSERT INTO `cd` (`CdId`,`Name`,`Description`,`Price`,`Quantity`,`Genre`,`Artist`,`Year`,`Rating`,`Review`,`Language`,`NumberOfTrack`,`AlbumArt`,`IsCdActive`) VALUES (1003,'Hotel California','Hotel California is the fifth studio album by the American rock band Eagles, released on Asylum in late 1976. It is the first Eagles album without the appearance of their founding member Bernie Leadon and their first album with guitarist Joe Walsh.',17,5,'Rock','The Eagles',1976,'Excellent','Excellent Music','English',9,NULL,1);
INSERT INTO `cd` (`CdId`,`Name`,`Description`,`Price`,`Quantity`,`Genre`,`Artist`,`Year`,`Rating`,`Review`,`Language`,`NumberOfTrack`,`AlbumArt`,`IsCdActive`) VALUES (1004,'Bleeding Heart','Bleeding Heart is one of several names given to albums of a 1968 jam session with Jimi Hendrix, Jim Morrison, and others. The albums were fashioned from an informal two-track tape recording made by Hendrix that was subsequently stolen from his apartment',15,4,'Blues','Jimi Hendrix',1994,'Good','Soothing','English',8,NULL,1);
INSERT INTO `cd` (`CdId`,`Name`,`Description`,`Price`,`Quantity`,`Genre`,`Artist`,`Year`,`Rating`,`Review`,`Language`,`NumberOfTrack`,`AlbumArt`,`IsCdActive`) VALUES (1005,'Kandisa','Kandisa is the second studio album released by Indian fusion band Indian Ocean in March 2000. It went on to become one of the best-loved albums produced in India',20,15,'Blues','Indian Ocean',2000,'Excellent','Heavenly','Hindi',7,NULL,1);
INSERT INTO `cd` (`CdId`,`Name`,`Description`,`Price`,`Quantity`,`Genre`,`Artist`,`Year`,`Rating`,`Review`,`Language`,`NumberOfTrack`,`AlbumArt`,`IsCdActive`) VALUES (1006,'Tailgates & Tanlines','Tailgates & Tanlines is the third studio album by American country music artist Luke Bryan. It was released on August 9, 2011, via Capitol Nashville',8,12,'Country','Luke Bryan',2001,'Average','This is okay','English',14,NULL,1);
INSERT INTO `cd` (`CdId`,`Name`,`Description`,`Price`,`Quantity`,`Genre`,`Artist`,`Year`,`Rating`,`Review`,`Language`,`NumberOfTrack`,`AlbumArt`,`IsCdActive`) VALUES (1007,'Just as I Am','Just as I Am is the third studio album by American country rock artist Brantley Gilbert. It was released on May 19, 2014 via Valory Music Group',9,20,'Country','Brantley Gilbert',2014,'Average','Can be better','English',11,NULL,1);
INSERT INTO `cd` (`CdId`,`Name`,`Description`,`Price`,`Quantity`,`Genre`,`Artist`,`Year`,`Rating`,`Review`,`Language`,`NumberOfTrack`,`AlbumArt`,`IsCdActive`) VALUES (1008,'The Best of Lucky Ali','he Best of Lucky Ali is a compilation album by Lucky Ali. The album released in 2005. It was released under the label Sony',15,10,'Pop','Lucky Ali',2005,'Very Good','Soulful Music','Hindi',11,NULL,1);
INSERT INTO `cd` (`CdId`,`Name`,`Description`,`Price`,`Quantity`,`Genre`,`Artist`,`Year`,`Rating`,`Review`,`Language`,`NumberOfTrack`,`AlbumArt`,`IsCdActive`) VALUES (1009,'Tomorrow\'s Harvest','Tomorrow\'s Harvest is the fourth studio album by the Scottish electronic music duo Boards of Canada, released on 5 June 2013 on Warp',14,5,'Electronic','Boards of Canada',2013,'Good','Good for party','English',17,NULL,1);
INSERT INTO `cd` (`CdId`,`Name`,`Description`,`Price`,`Quantity`,`Genre`,`Artist`,`Year`,`Rating`,`Review`,`Language`,`NumberOfTrack`,`AlbumArt`,`IsCdActive`) VALUES (1010,'In Colour','In Colour is the debut studio album by English record producer and The xx member Jamie Smith, better known as Jamie xx, released on 29 May 2015 by Young Turks',13,6,'Electronic','Jamie xx',2015,'Average','Average','English',11,NULL,1);
