package com.musephoria.entity;
// default package
// Generated Oct 24, 2015 10:30:11 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cartitem generated by hbm2java
 */
@Entity
@Table(name = "cartitem", catalog = "musephoria", uniqueConstraints = { @UniqueConstraint(columnNames = "CdId"),
		@UniqueConstraint(columnNames = "CartId") })
public class Cartitem implements java.io.Serializable {

	private Integer cartItemId;
	private Cd cd;
	private Cart cart;
	private String cardItemName;
	private int quantity;
	private float baseAmount;

	public Cartitem() {
	}

	public Cartitem(Cd cd, Cart cart, String cardItemName, int quantity, float baseAmount) {
		this.cd = cd;
		this.cart = cart;
		this.cardItemName = cardItemName;
		this.quantity = quantity;
		this.baseAmount = baseAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CartItemId", unique = true, nullable = false)
	public Integer getCartItemId() {
		return this.cartItemId;
	}

	public void setCartItemId(Integer cartItemId) {
		this.cartItemId = cartItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CdId", unique = true, nullable = false)
	public Cd getCd() {
		return this.cd;
	}

	public void setCd(Cd cd) {
		this.cd = cd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CartId", unique = true, nullable = false)
	public Cart getCart() {
		return this.cart;
	}

	public void setCart(Cart cart) {
		this.cart = cart;
	}

	@Column(name = "CardItemName", nullable = false, length = 45)
	public String getCardItemName() {
		return this.cardItemName;
	}

	public void setCardItemName(String cardItemName) {
		this.cardItemName = cardItemName;
	}

	@Column(name = "Quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "BaseAmount", nullable = false, precision = 12, scale = 0)
	public float getBaseAmount() {
		return this.baseAmount;
	}

	public void setBaseAmount(float baseAmount) {
		this.baseAmount = baseAmount;
	}

}
