package com.musephoria.entity;
// Generated Oct 19, 2015 11:46:19 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cartitem generated by hbm2java
 */
@Entity
@Table(name = "cartitem", catalog = "musephoria", uniqueConstraints = { @UniqueConstraint(columnNames = "CartId"),
		@UniqueConstraint(columnNames = "CdId") })
@SuppressWarnings("serial")
public class Cartitem implements java.io.Serializable {

	private Integer cartItemId;
	private Cart cart;
	private Cd cd;
	private Integer quantity;
	private float baseAmount;

	public Cartitem() {
	}

	public Cartitem(Cart cart, Cd cd, float baseAmount) {
		this.cart = cart;
		this.cd = cd;
		this.baseAmount = baseAmount;
	}

	public Cartitem(Cart cart, Cd cd, Integer quantity, float baseAmount) {
		this.cart = cart;
		this.cd = cd;
		this.quantity = quantity;
		this.baseAmount = baseAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CartItemId", unique = true, nullable = false)
	public Integer getCartItemId() {
		return this.cartItemId;
	}

	public void setCartItemId(Integer cartItemId) {
		this.cartItemId = cartItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CartId", unique = true, nullable = false)
	public Cart getCart() {
		return this.cart;
	}

	public void setCart(Cart cart) {
		this.cart = cart;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CdId", unique = true, nullable = false)
	public Cd getCd() {
		return this.cd;
	}

	public void setCd(Cd cd) {
		this.cd = cd;
	}

	@Column(name = "Quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "BaseAmount", nullable = false, precision = 12, scale = 0)
	public float getBaseAmount() {
		return this.baseAmount;
	}

	public void setBaseAmount(float baseAmount) {
		this.baseAmount = baseAmount;
	}

}
