package com.musephoria.entity;
// Generated Oct 19, 2015 11:46:19 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Customerdetail generated by hbm2java
 */
@Entity
@Table(name = "customerdetail", catalog = "musephoria", uniqueConstraints = @UniqueConstraint(columnNames = "CustomerId") )
@SuppressWarnings("serial")
public class Customerdetail implements java.io.Serializable {

	private int customerDetailId;
	private Customer customer;
	private String customerName;
	private String address;
	private String city;
	private String province;
	private String country;
	private String zipCode;
	private String email;
	private String phone;
	private boolean isShipppingAddress;

	public Customerdetail() {
	}

	public Customerdetail(int customerDetailId, Customer customer, String customerName, String address, String city,
			String province, String country, String zipCode, String email, String phone, boolean isShipppingAddress) {
		this.customerDetailId = customerDetailId;
		this.customer = customer;
		this.customerName = customerName;
		this.address = address;
		this.city = city;
		this.province = province;
		this.country = country;
		this.zipCode = zipCode;
		this.email = email;
		this.phone = phone;
		this.isShipppingAddress = isShipppingAddress;
	}

	@Id

	@Column(name = "CustomerDetailId", unique = true, nullable = false)
	public int getCustomerDetailId() {
		return this.customerDetailId;
	}

	public void setCustomerDetailId(int customerDetailId) {
		this.customerDetailId = customerDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CustomerId", unique = true, nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "CustomerName", nullable = false, length = 45)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "Address", nullable = false, length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "City", nullable = false, length = 25)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "Province", nullable = false, length = 25)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "Country", nullable = false, length = 25)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "ZipCode", nullable = false, length = 6)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "Email", nullable = false, length = 25)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Phone", nullable = false, length = 10)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "IsShipppingAddress", nullable = false)
	public boolean isIsShipppingAddress() {
		return this.isShipppingAddress;
	}

	public void setIsShipppingAddress(boolean isShipppingAddress) {
		this.isShipppingAddress = isShipppingAddress;
	}

}
