package com.musephoria.entity;
// default package

// Generated Oct 24, 2015 10:30:11 PM by Hibernate Tools 4.0.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Orderitem generated by hbm2java
 */
@Entity
@Table(name = "orderitem", catalog = "musephoria")
@SuppressWarnings("serial")
public class Orderitem implements java.io.Serializable {

	private Integer orderItemId;
	private Order order;
	private Cd cd;
	private String orderItemName;
	private int orderQuantity;

	public Orderitem() {
	}

	public Orderitem(Order order, Cd cd, String orderItemName, int orderQuantity) {
		this.order = order;
		this.cd = cd;
		this.orderItemName = orderItemName;
		this.orderQuantity = orderQuantity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OrderItemId", unique = true, nullable = false)
	public Integer getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(Integer orderItemId) {
		this.orderItemId = orderItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OrderId", nullable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CdId", nullable = false)
	public Cd getCd() {
		return this.cd;
	}

	public void setCd(Cd cd) {
		this.cd = cd;
	}

	@Column(name = "OrderItemName", nullable = false, length = 45)
	public String getOrderItemName() {
		return this.orderItemName;
	}

	public void setOrderItemName(String orderItemName) {
		this.orderItemName = orderItemName;
	}

	@Column(name = "OrderQuantity", nullable = false)
	public int getOrderQuantity() {
		return this.orderQuantity;
	}

	public void setOrderQuantity(int orderQuantity) {
		this.orderQuantity = orderQuantity;
	}

}
