package com.musephoria.entity;
// Generated Oct 19, 2015 11:46:19 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", catalog = "musephoria")
@SuppressWarnings("serial")
public class Payment implements java.io.Serializable {

	private Integer paymentId;
	private Date timeStamp;
	private Customer customer;
	private String cardType;
	private int cardNumber;
	private int expriyMonth;
	private int expirtyYear;
	private int cvv;
	private String nameOnCard;

	public Payment() {
	}

	public Payment(Customer customer, String cardType, int cardNumber, int expriyMonth, int expirtyYear, int cvv,
			String nameOnCard) {
		this.customer = customer;
		this.cardType = cardType;
		this.cardNumber = cardNumber;
		this.expriyMonth = expriyMonth;
		this.expirtyYear = expirtyYear;
		this.cvv = cvv;
		this.nameOnCard = nameOnCard;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PaymentId", unique = true, nullable = false)
	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TimeStamp", nullable = false, length = 19)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CustomerId", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "CardType", nullable = false, length = 7)
	public String getCardType() {
		return this.cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	@Column(name = "CardNumber", nullable = false)
	public int getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(int cardNumber) {
		this.cardNumber = cardNumber;
	}

	@Column(name = "ExpriyMonth", nullable = false)
	public int getExpriyMonth() {
		return this.expriyMonth;
	}

	public void setExpriyMonth(int expriyMonth) {
		this.expriyMonth = expriyMonth;
	}

	@Column(name = "ExpirtyYear", nullable = false)
	public int getExpirtyYear() {
		return this.expirtyYear;
	}

	public void setExpirtyYear(int expirtyYear) {
		this.expirtyYear = expirtyYear;
	}

	@Column(name = "CVV", nullable = false)
	public int getCvv() {
		return this.cvv;
	}

	public void setCvv(int cvv) {
		this.cvv = cvv;
	}

	@Column(name = "NameOnCard", nullable = false, length = 45)
	public String getNameOnCard() {
		return this.nameOnCard;
	}

	public void setNameOnCard(String nameOnCard) {
		this.nameOnCard = nameOnCard;
	}

}
