package com.musephoria.entity;
// default package

// Generated Oct 29, 2015 12:25:05 AM by Hibernate Tools 4.0.0.Final

import java.util.Date;

import javax.persistence.Entity;

/**
 * Paymentinfo generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
public class Paymentinfo implements java.io.Serializable {

	private Integer paymentInfoId;
	private Date timeStamp;
	private Customer customer;
	private int cardNumber;
	private String paymentInfoStatus;

	public Paymentinfo() {
	}

	public Paymentinfo(Customer customer, int cardNumber, String paymentInfoStatus) {
		this.customer = customer;
		this.cardNumber = cardNumber;
		this.paymentInfoStatus = paymentInfoStatus;
	}

	public Integer getPaymentInfoId() {
		return this.paymentInfoId;
	}

	public void setPaymentInfoId(Integer paymentInfoId) {
		this.paymentInfoId = paymentInfoId;
	}

	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public int getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(int cardNumber) {
		this.cardNumber = cardNumber;
	}

	public String getPaymentInfoStatus() {
		return this.paymentInfoStatus;
	}

	public void setPaymentInfoStatus(String paymentInfoStatus) {
		this.paymentInfoStatus = paymentInfoStatus;
	}

}
