package com.musephoria.entity;
// default package
// Generated Oct 29, 2015 12:25:05 AM by Hibernate Tools 4.0.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Purchaseorderitem generated by hbm2java
 */
@Entity
@Table(name = "purchaseorderitem", catalog = "musephoria")
@SuppressWarnings("serial")
public class Purchaseorderitem implements java.io.Serializable {

	private Integer purchaseOrderItemId;
	private Purchaseorder purchaseorder;
	private Cd cd;
	private String purchaseOrderItemName;
	private float baseAmount;

	public Purchaseorderitem() {
	}

	public Purchaseorderitem(Purchaseorder purchaseorder, Cd cd, String purchaseOrderItemName, float baseAmount) {
		this.purchaseorder = purchaseorder;
		this.cd = cd;
		this.purchaseOrderItemName = purchaseOrderItemName;
		this.baseAmount = baseAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PurchaseOrderItemId", unique = true, nullable = false)
	public Integer getPurchaseOrderItemId() {
		return this.purchaseOrderItemId;
	}

	public void setPurchaseOrderItemId(Integer purchaseOrderItemId) {
		this.purchaseOrderItemId = purchaseOrderItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PurchaseOrderId", nullable = false)
	public Purchaseorder getPurchaseorder() {
		return this.purchaseorder;
	}

	public void setPurchaseorder(Purchaseorder purchaseorder) {
		this.purchaseorder = purchaseorder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CdId", nullable = false)
	public Cd getCd() {
		return this.cd;
	}

	public void setCd(Cd cd) {
		this.cd = cd;
	}

	@Column(name = "PurchaseOrderItemName", nullable = false, length = 45)
	public String getPurchaseOrderItemName() {
		return this.purchaseOrderItemName;
	}

	public void setPurchaseOrderItemName(String purchaseOrderItemName) {
		this.purchaseOrderItemName = purchaseOrderItemName;
	}

	@Column(name = "BaseAmount", nullable = false, precision = 12, scale = 0)
	public float getBaseAmount() {
		return this.baseAmount;
	}

	public void setBaseAmount(float baseAmount) {
		this.baseAmount = baseAmount;
	}

}
