package com.musephoria.entity;
// default package
// Generated Nov 1, 2015 11:57:06 AM by Hibernate Tools 4.0.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Purchaseorder generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "purchaseorder", catalog = "musephoria")
public class Purchaseorder implements java.io.Serializable {

	private Integer purchaseOrderId;
	private Integer customerId;
	private Integer totalQuantity;
	private Float totalPrice;
	private Float taxes;
	private String purchaseOrderStatus;
	private Set<Purchaseorderitem> purchaseorderitems = new HashSet<Purchaseorderitem>(0);
	private Set<Shipping> shippings = new HashSet<Shipping>(0);

	public Purchaseorder() {
	}

	public Purchaseorder(Integer customerId, Integer totalQuantity, Float totalPrice, Float taxes,
			String purchaseOrderStatus, Set<Purchaseorderitem> purchaseorderitems, Set<Shipping> shippings) {
		this.customerId = customerId;
		this.totalQuantity = totalQuantity;
		this.totalPrice = totalPrice;
		this.taxes = taxes;
		this.purchaseOrderStatus = purchaseOrderStatus;
		this.purchaseorderitems = purchaseorderitems;
		this.shippings = shippings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PurchaseOrderId", unique = true, nullable = false)
	public Integer getPurchaseOrderId() {
		return this.purchaseOrderId;
	}

	public void setPurchaseOrderId(Integer purchaseOrderId) {
		this.purchaseOrderId = purchaseOrderId;
	}

	@Column(name = "CustomerId")
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "TotalQuantity")
	public Integer getTotalQuantity() {
		return this.totalQuantity;
	}

	public void setTotalQuantity(Integer totalQuantity) {
		this.totalQuantity = totalQuantity;
	}

	@Column(name = "TotalPrice", precision = 12, scale = 0)
	public Float getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(Float totalPrice) {
		this.totalPrice = totalPrice;
	}

	@Column(name = "Taxes", precision = 12, scale = 0)
	public Float getTaxes() {
		return this.taxes;
	}

	public void setTaxes(Float taxes) {
		this.taxes = taxes;
	}

	@Column(name = "PurchaseOrderStatus", length = 8)
	public String getPurchaseOrderStatus() {
		return this.purchaseOrderStatus;
	}

	public void setPurchaseOrderStatus(String purchaseOrderStatus) {
		this.purchaseOrderStatus = purchaseOrderStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "purchaseorder")
	public Set<Purchaseorderitem> getPurchaseorderitems() {
		return this.purchaseorderitems;
	}

	public void setPurchaseorderitems(Set<Purchaseorderitem> purchaseorderitems) {
		this.purchaseorderitems = purchaseorderitems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "purchaseorder")
	public Set<Shipping> getShippings() {
		return this.shippings;
	}

	public void setShippings(Set<Shipping> shippings) {
		this.shippings = shippings;
	}

}
