package com.musephoria.entity;
// default package
// Generated Nov 1, 2015 11:57:06 AM by Hibernate Tools 4.0.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Shipping generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "shipping", catalog = "musephoria")
public class Shipping implements java.io.Serializable {

	private Integer shippingId;
	private Purchaseorder purchaseorder;
	private String address;
	private String city;
	private String province;
	private String country;
	private String zipCode;
	private String phone;
	private Boolean isShippingActive;

	public Shipping() {
	}

	public Shipping(Purchaseorder purchaseorder, String address, String city, String province, String country,
			String zipCode, String phone, Boolean isShippingActive) {
		this.purchaseorder = purchaseorder;
		this.address = address;
		this.city = city;
		this.province = province;
		this.country = country;
		this.zipCode = zipCode;
		this.phone = phone;
		this.isShippingActive = isShippingActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ShippingId", unique = true, nullable = false)
	public Integer getShippingId() {
		return this.shippingId;
	}

	public void setShippingId(Integer shippingId) {
		this.shippingId = shippingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PurchaseOrderId")
	public Purchaseorder getPurchaseorder() {
		return this.purchaseorder;
	}

	public void setPurchaseorder(Purchaseorder purchaseorder) {
		this.purchaseorder = purchaseorder;
	}

	@Column(name = "Address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "City", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "Province", length = 45)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "Country", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "ZipCode", length = 7)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "Phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "IsShippingActive")
	public Boolean getIsShippingActive() {
		return this.isShippingActive;
	}

	public void setIsShippingActive(Boolean isShippingActive) {
		this.isShippingActive = isShippingActive;
	}

}
